@component('mail::message')
Hello **{{ $data->user->name }}**,

@if(strlen($data->event->kicker) > 0)
Thank you for registering to **{{ $data->event->kicker }} {{ $data->event->name }}**.
@else
Thank you for registering to **{{ $data->event->name }}**.
@endif

Here's your payment invoice for the event ticket(s).

@component('mail::panel')
+ **Payment Code:** {{ $data->registration->payment_code }}
+ **Price:** {{ $data->registration->total_price }}
@endcomponent

Please follow the payment instructions below:

@component('mail::panel')
{{ $data->event->description_pending }}
@endcomponent

then proceed to [{{ env('APP_URL') }}/pay/{{ $data->registration->payment_code }}]({{ env('APP_URL') }}/pay/{{ $data->registration->payment_code }}) to upload the receipt. You can also request others to pay as long as they are logged in to a {{ env('APP_NAME') }} account by using the same link.

@component('mail::button', ['url' => (strlen($data->event->payment_link) > 0) ? $data->event->payment_link : (env('APP_URL') . '/pay/' . $data->registration->payment_code)])
Upload Receipt
@endcomponent

Sincerely,
@if(strlen($data->event->kicker) > 0)
{{ $data->event->kicker }} event committee.
@else
{{ $data->event->name }} event committee.
@endif

---

### Notice

This is an autogenerated email message from **{{ env('APP_NAME') }}** system. Please **do not** reply to this message.

If you encounter any problems, please contact the respective event committees.
@endcomponent
