@component('mail::message')
Hello **{{$data["name"]}}**,
Thank you for registering to {{$data["event_name"]}}!

You are recently being added by **{{$data["team_leader_name"]}}** ({{$data["team_leader_email"]}}) as **{{$data["role"]}}** for **{{$data["event_name"]}}**.

@component('mail::panel')
+ **Team ID:** {{$data["team_id"]}}
+ **Team Name:** {{$data["team_name"]}}
@endcomponent

Please kindly contact us if you think this is a mistake or an abuse. Thank you for your attention.

Sincerely,
@if(strlen($data["event_kicker"]) > 0)
{{ $data["event_kicker"] }} event committee.
@else
{{ $data["event_name"] }} event committee.
@endif

---

### Notice

This is an autogenerated email message from **{{ env('APP_NAME') }}** system. Please **do not** reply to this message.

If you encounter any problems, please contact the respective event committees.
@endcomponent
